### ISSUE TITLE
Only apply low gravity when holding jump while player has positive y velocity

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#14]

**Comment by Noah2610** [comment]
Switches to normal player gravity, if the player's `y` velocity is below `0.0` (this value should eventually be configurable via a settings file).

---

Player gravity now depends on the player's `y` velocity and if the jump button is being pressed, instead of if the player is currently in the "jumping" state.
This means, for example, if the player is jumping on a jumppad, they release the jump button and re-press it again, then the jump gravity will be used again. Previously, the jump gravity would only be used after the player jumped and while they didn't let go of the jump button.
