### ISSUE TITLE
Entities fall through jumppads

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#28]
If an entitiy (player or enemy) triggers a jumppad while it can't move vertically (-> while the velocity that is being applied to it by the jumppad can't be "executed") (for example because another solid entitity is located **directly** above it), the entitiy simply falls through the jumppad. 

(reproducable, consistent)
(low priority)

**Comment by Noah2610** [comment]
Jumppad tiles aren't solid, which means other solid entities (like that one enemy) can push the player (or other jummpad-affected entities) through the jumppad.

__Possible solutions:__
- Make Jumppads solid.  
  Jumppad collision checking would have to be adjusted, and would probably have to assume that the tile is solid.
- ~~Don't use Jumppad component.  
  Instead, configure event/actions to recreate the same behaviour, for each tile that needs it. This allows for way more flexibility, as collision checking can be adjusted per entity, instead of the Jumppad code needing to assume stuff, like that the entity is solid.  
  This obviously depends on me adding the events/actions system to tile configs first.~~  
  After more thought, this makes no sense as the jumppad.

I'll work on making solid jumppads work.

**Comment by Noah2610** [comment]
Works for now, could probably be made solid via config, but probably also unnecessary.
